name: flutter_column
description: expandable flutter column
version: 0.1.0+1


environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  very_good_analysis: 7.0.0
